### ISSUE TITLE
Use Midje 1.6.3

### ISSUE THREAD

**Issue by chetmancini** [marick/lein-midje#54]
I'm seeing the `clojure.core.record?` issue that was closed here:
https://github.com/marick/Midje/issues/264

I presume bumping to 1.6.3 would resolve?

**Comment by rwobben** [comment]
any idea when this error is solved. I have now clojure 1.7.0 and lein-midje 3.2-rc4 and the problem is still here.

**Comment by marick** [comment]
It doesn't happen with Midje 1.7

**Comment by rwobben** [comment]
I do not know, Im using a old project which uses lein-midje and when I use the last lein-midje the problem still are there.

**Comment by marick** [comment]
I suspect you are using an old version of Midje. The latest stable release is [midje "1.7.0"].

**Comment by rwobben** [comment]
no idea. How can I check ? In my project.cli only lein-midje is mentioned

**Comment by marick** [comment]
If midje isn't mentioned, you should mention it explicitly, as 

```
  :profiles {:dev {:dependencies [[midje "1.8-alpha1" :exclusions [org.clojure/clojure]]
                                  [org.blancas/morph "0.3.0" :exclusions [org.clojure/clojure]]
                                  [com.taoensso/timbre "4.1.1" :exclusions [org.clojure/clojure]]
```
