### ISSUE TITLE
filtering multiple values

### ISSUE THREAD

**Issue by narkisr** [marick/lein-midje#57]
Running:

lein midje :filter -integration -agent 

Results with integration test running ignoring the filtering

**Comment by marick** [comment]
This is the way it's defined to work. Individual tokens are combined with OR. Therefore:

```clojure
(fact :agent   ;; this runs because it's "not integration"
  :agent => :failed)

(fact :integration  ;; This runs because it's "not agent"
  :integration => :failed)
```
This is counterintuitive in this case, but I argue AND would be counterintuitive in the case of the non-negated form. 

The solution is to put this in a file, say `fast.config`:

```clojure
(change-defaults :fact-filter #(and (not (:agent %))
                                    (not (:integration %))))
```

... and then run `lein midje` like this:

```
581 $ lein midje :config fast.config
```

**Comment by marick** [comment]
I'll update the documentation.

**Comment by narkisr** [comment]
Ok thanks
