### ISSUE TITLE
lein-midge 3.2-RC4 not working with midge-1.8-alpha

### ISSUE THREAD

**Issue by jr0cket** [marick/lein-midje#58]
I set the plugin for lein-midge 3.2-RC4 in my `~/.lein/profiles.clj`, when running `lein new` or `lein deps` the following error messages are shown

```
Could not find artifact midje:midje:jar:1.8-alpha in central (https://repo1.maven.org/maven2/)
Could not find artifact midje:midje:jar:1.8-alpha in clojars (https://clojars.org/repo/)
```
Using version 3.2-RC3 works without issue.

I tried switching back to `3.2-RC4` after creating a project and I still get the same error.  I have also tried `lein clean` and it makes no difference.

The `project.clj` file for the project is as follows

```
(defproject fun-with-midje "0.0.1-SNAPSHOT"
  :description "Trying out Midje library for TDD fun"
  :dependencies [[org.clojure/clojure "1.7.0"]]
  :profiles {:dev {:dependencies [[midje "1.8-alpha"]]}})
```

**Comment by marick** [comment]
Terribly sorry for the delay, especially because the problem was just a typo. There is no `1.8-alpha`. It's `1.8-alpha1`

**Comment by jr0cket** [comment]
Thanks.  I had assumed it was something like a typo, I just wasn't sure where.  I was able to do what I needed with the earlier version, so not a blocker for me.
