### ISSUE TITLE
WARNING: any? already refers to: #'clojure.core/any? in namespace: leiningen.midje, being replaced by: #'leiningen.midje/any?

### ISSUE THREAD

**Issue by jsyrjala** [marick/lein-midje#67]
Running `lein midje` with Clojure 1.10.1, Leiningen 2.9.1 and lein-midje 3.2.1 gives this warning:

```
WARNING: any? already refers to: #'clojure.core/any? in namespace: leiningen.midje, being replaced by: #'leiningen.midje/any?
```

Probably related to this function name:
https://github.com/marick/lein-midje/blob/master/src/leiningen/midje.clj#L57
https://github.com/marick/lein-midje/blob/master/src/leiningen/midje.clj#L88

**Comment by Em-AK** [comment]
Hi @philomates, I think this issue can be closed. As it is solved in #69
