### ISSUE TITLE
Cannot get midje to run in repl

### ISSUE THREAD

**Issue by 573** [marick/lein-midje#68]
Hello and congrats to a great project,

I cannot get a certain thing to run though:

> $ lein update-in :dependencies conj '[lein-midje "3.0.0"]' -- repl
> user=> (use 'midje.repl)
>
> FileNotFoundException Could not locate midje/repl__init.class or midje/repl.clj on classpath.  clojure.lang.RT.load (RT.java:456)

Seems related to #34 but IDK hwo to bind the 1.5-alpha5 right away in lein repl. Is that possible inside the repl or is a profile file crucial?

**Comment by philomates** [comment]
Hello!
Could you try using the latest version of `lein-midje` to see if the issue persists?  I believe it is `'[lein-midje "3.2.1"]'`. You could also try to see if being on the latest version of `midje` helps (`1.9.8`)

**Comment by 573** [comment]
Wow, thanks @philomates, [got it](https://pastebin.com/kb4MmUWb) to run in `repl`:

> $ lein update-in :dependencies conj '[midje "1.9.8"]' -- update-in :plugins conj '[lein-midje "3.2.1"]' -- repl
